### PR TITLE
gt_console: swap language in interactive mode

### PR DESCRIPTION
**Pull request by siikamiika**
Use "<" to switch between the languages in interactive mode.

### CODE REVIEW

**Comment by shdown** [comment]
Probably it would be nicer to implement a set of commands, https://github.com/soimort/translate-shell/wiki/REPL -like.

I'm not sure if I want to merge this.

**Comment by siikamiika** [comment]
I see. Some things I have in mind:
  - `::-1` to swap the languages, possibly with a prefix, if that would make any sense. `en:fi` to completely override.
  - The Google Translate Android app swaps the languages if you change the source language to the target language. So, if the present translation configuration was `ja:en`, using `en:` would swap them.

Are you thinking of using the locale like translate-shell?

**Comment by shdown** [comment]
> Are you thinking of using the locale like translate-shell?

If this is about guessing which languages a user has meant, instead of requiring passing two ones explicitly -- probably not. One can just use shell aliases/wrapper scripts for this.

Maybe deducing `-L`/`--inteface-lang` from $LANG or something is OK, but what about other strings (headers, messages etc) then? Should we leave them untranslated?

---

A scratch of a set of commands I'm thinking of:
```
:command[ :command ...][ text]
If "text" is given, it is translated and commands are only applied for this translation.
List of commands:
    >LANG        -- set source language
    <LANG        -- set target language
    LANG>LANG    -- set both source and target langauges
    r            -- swap languages
    -LETTER      -- enable an option represented by LETTER
    +LETTER      -- disable an option represented by LETTER
Examples:
    :ru>en            -- set source language to Russian and target language to English
    :<en :-r hello    -- translate "hello" from English and only show result
    :+e               -- don't show examples anymore
```

**Comment by shdown** [comment]
> As for --interface-lang, guessing the language would be nice, but it would have to be made sure that using $LANG wouldn't break it for anyone. It would also make porting to other platforms more difficult.

Yep.

> using :>DESTLANG and :SRCLANG> instead of :<DESTLANG to keep in consistent with the :SRC>DEST syntax

OK, accepted.

> using + to remove something doesn't seem that intuitive

That was a parallel to bash's `set` builtin, which uses this notation (`-letter` for enabling and `+letter` for disabling) because `-letter` is a usual way to enable something in UNIX command-line tools (including gt_console). Maybe `:LETTER` for enabling, `:-LETTER` for disabling and `:swap` for swapping langauges?

**Comment by siikamiika** [comment]
> That was a parallel to bash's set builtin, which uses this notation (-letter for enabling and +letter for disabling) because -letter is a usual way to enable something in UNIX command-line tools (including gt_console). Maybe :LETTER for enabling, :-LETTER for disabling and :swap for swapping langauges?

Ah, I wasn't aware of this. I use python to write shell scripts :D
In that case it would be just fine to use + for disabling and - for enabling options. For language swapping I would stay with my original commit and use `:<`. Why not some alias like `:swap` as well.

**Comment by shdown** [comment]
Done in the `commands` branch. Possible TODOs are to show active "option letters" in prompt and allow prompt customization.

**Comment by siikamiika** [comment]
Nice work! So much more comfortable to use now that you don't need to exit the prompt to switch the languages or change options.

To allow changing multiple options at once (like `-tT`) you could loop through the letters at https://github.com/shdown/gt/commit/f643899db21ffc32f08549d1c105fc0ca2609715#diff-7e1224bb606ed6b160e91c00866fba6eR354 but what about verbose options?

**Comment by shdown** [comment]
> To allow changing multiple options at once (like -tT) you could loop through the letters at f643899#diff-7e1224bb606ed6b160e91c00866fba6eR354

Accepted.

> what about verbose options?

Do you mean we should allow setting options by their verbose names? I'm not sure if this is needed. 
Maybe introduce `:h`/`:help` command that shows the option list instead?...

**Comment by siikamiika** [comment]
That's right, it's not so important if the list of commands stays relatively short. I wasn't really even suggesting that now that I think back. It was more like me writing before thinking; I thought that looping the characters wouldn't work together with verbose options but of course if they were added they would be preceded by two dashes or plus signs, not one.

Help is always good to have but as mentioned there aren't that many commands so do as you feel best with that :)

**Comment by shdown** [comment]
Interactive-mode commands are in master now, so I close this.

**Pull request closed without merging**
